apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: synapse.<REPLACE_WITH_SYNAPSE_HOMESERVER>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: synapse
                port: 
                  # example using port name
                  name: synapse
