apiVersion: v1
kind: Service
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  type: ClusterIP
  ports:
    - port: 8008
      targetPort: 8008
      name: synapse
  selector:
    app: synapse
