apiVersion: v1
kind: Service
metadata:
  name: element
  labels:
    app: element
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: element
  selector:
    app: element
