# The file upload settings for the media repository
uploads:
  # The maximum individual file size a user can upload.
  maxBytes: 104857600 # 100MB default, 0 to disable
                                                                                                   
  # The minimum number of bytes to let people upload. This is recommended to be non-zero to
  # ensure that the "cost" of running the media repo is worthwhile - small file uploads tend
  # to waste more CPU and database resources than small files, thus a default of 100 bytes
  # is applied here as an approximate break-even point.
  minBytes: 100 # 100 bytes by default
                                                                                                   
  # The number of bytes to claim as the maximum size for uploads for the limits API. If this
  # is not provided then the maxBytes setting will be used instead. This is useful to provide
  # if the media repo's settings and the reverse proxy do not match for maximum request size.
  # This is purely for informational reasons and does not actually limit any functionality.
  # Set this to -1 to indicate that there is no limit. Zero will force the use of maxBytes.
  #reportedMaxBytes: 104857600
                                                                                                   
  # Options for limiting how much content a user can upload. Quotas are applied to content
  # associated with a user regardless of de-duplication. Quotas which affect remote servers
  # or users will not take effect. When a user exceeds their quota they will be unable to
  # upload any more media.
  quotas:
    # Whether or not quotas are enabled/enforced. Note that even when disabled the media repo
    # will track how much media a user has uploaded. This is disabled by default.
    enabled: false
                                                                                                   
    # The quota rules that affect users. The first rule to match the uploader will take effect.
    # An implied rule which matches all users and has no quota is always last in this list,
    # meaning that if no rules are supplied then users will be able to upload anything. Similarly,
    # if no rules match a user then the implied rule will match, allowing the user to have no
    # quota. The quota will let the user upload to 1 media past their quota, meaning that from
    # a statistics perspective the user might exceed their quota however only by a small amount.
    users:
      - glob: "@*:*"  # Affect all users. Use asterisks (*) to match any character.
        maxBytes: 53687063712 # 50GB default, 0 to disable
