apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mmr-psql
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "mmr-psql"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: mmr-psql
          image: postgres:12.3
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mmr-db-secrets
                  key: postgres-password
            - name: POSTGRES_USER
              value: mediarepo
            - name: POSTGRES_DB
              value: mediarepo
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: mmrpsql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: mmrpsql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName:
        resources:
          requests:
            storage: 100M
