## Account Validity ##

# Optional account validity configuration. This allows for accounts to be denied
# any request after a given period.
#
# Once this feature is enabled, Synapse will look for registered users without an
# expiration date at startup and will add one to every account it found using the
# current settings at that time.
# This means that, if a validity period is set, and Synapse is restarted (it will
# then derive an expiration date from the current validity period), and some time
# after that the validity period changes and Synapse is restarted, the users'
# expiration dates won't be updated unless their account is manually renewed. This
# date will be randomly selected within a range [now + period - d ; now + period],
# where d is equal to 10% of the validity period.
#
account_validity:
  # The account validity feature is disabled by default. Uncomment the
  # following line to enable it.
  #
  #enabled: true

  # The period after which an account is valid after its registration. When
  # renewing the account, its validity period will be extended by this amount
  # of time. This parameter is required when using the account validity
  # feature.
  #
  #period: 6w

  # The amount of time before an account's expiry date at which Synapse will
  # send an email to the account's email address with a renewal link. By
  # default, no such emails are sent.
  #
  # If you enable this setting, you will also need to fill out the 'email' and
  # 'public_baseurl' configuration sections.
  #
  #renew_at: 1w

  # The subject of the email sent out with the renewal link. '%(app)s' can be
  # used as a placeholder for the 'app_name' parameter from the 'email'
  # section.
  #
  # Note that the placeholder must be written '%(app)s', including the
  # trailing 's'.
  #
  # If this is not set, a default value is used.
  #
  #renew_email_subject: "Renew your %(app)s account"

  # Directory in which Synapse will try to find templates for the HTML files to
  # serve to the user when trying to renew an account. If not set, default
  # templates from within the Synapse package will be used.
  #
  # The currently available templates are:
  #
  # * account_renewed.html: Displayed to the user after they have successfully
  #       renewed their account.
  #
  # * account_previously_renewed.html: Displayed to the user if they attempt to
  #       renew their account with a token that is valid, but that has already
  #       been used. In this case the account is not renewed again.
  #
  # * invalid_token.html: Displayed to the user when they try to renew an account
  #       with an unknown or invalid renewal token.
  #
  # See https://github.com/matrix-org/synapse/tree/master/synapse/res/templates for
  # default template contents.
  #
  # The file name of some of these templates can be configured below for legacy
  # reasons.
  #
  #template_dir: "res/templates"

  # A custom file name for the 'account_renewed.html' template.
  #
  # If not set, the file is assumed to be named "account_renewed.html".
  #
  #account_renewed_html_path: "account_renewed.html"

  # A custom file name for the 'invalid_token.html' template.
  #
  # If not set, the file is assumed to be named "invalid_token.html".
  #
  #invalid_token_html_path: "invalid_token.html"
