# This config gets overwritten by generate-overlays.sh
# This file is left here as a generic example
# The configuration for the homeservers this media repository is known to control. Servers
# not listed here will not be able to upload media.
homeservers:
  - name: example.org # This should match the server_name of your homeserver, and the Host header
                      # provided to the media repo.
    csApi: "https://example.org/" # The base URL to where the homeserver can actually be reached
    backoffAt: 10 # The number of consecutive failures in calling this homeserver before the
                  # media repository will start backing off. This defaults to 10 if not given.
    adminApiKind: "matrix" # The kind of admin API the homeserver supports. If set to "matrix",
                           # the media repo will use the Synapse-defined endpoints under the
                           # unstable client-server API. When this is "synapse", the new /_synapse
                           # endpoints will be used instead. Unknown values are treated as the
                           # default, "matrix".
