# Options for controlling various MSCs/unstable features of the media repo
# Sections of this config might disappear or be added over time. By default all
# features are disabled in here and must be explicitly enabled to be used.
featureSupport:
  # MSC2248 - Blurhash
  MSC2448:
    # Whether or not this MSC is enabled for use in the media repo
    enabled: false
                                                                                               
    # Maximum dimensions for converting a blurhash to an image. When no width and
    # height options are supplied, the default will be half these values.
    maxWidth: 1024
    maxHeight: 1024
                                                                                               
    # Thumbnail size in pixels to use to generate the blurhash string
    thumbWidth: 64
    thumbHeight: 64
                                                                                               
    # The X and Y components to use. Higher numbers blur less, lower numbers blur more.
    xComponents: 4
    yComponents: 3
                                                                                               
    # The amount of contrast to apply when converting a blurhash to an image. Lower values
    # make the effect more subtle, larger values make it stronger.
    punch: 1
                                                                                               
  # IPFS Support
  # This is currently experimental and might not work at all.
  IPFS:
    # Whether or not IPFS support is enabled for use in the media repo.
    enabled: false
                                                                                               
    # Options for the built in IPFS daemon
    builtInDaemon:
      # Enable this to spawn an in-process IPFS node to use instead of a localhost
      # HTTP agent. If this is disabled, the media repo will assume you have an HTTP
      # IPFS agent running and accessible. Defaults to using a daemon (true).
      enabled: true
                                                                                               
      # If the Daemon is enabled, set this to the location where the IPFS files should
      # be stored. If you're using Docker, this should be something like "/data/ipfs"
      # so it can be mapped to a volume.
      repoPath: "./ipfs"
