apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <REPLACE_WITH_PREFIX>mmr-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/upstream-vhost: <REPLACE_WITH_MMR_HOMESERVER>
spec:
  rules:
    - host: synapse.<REPLACE_WITH_MMR_HOMESERVER>
      http:
        paths:
          - path: /_matrix/media/
            pathType: Prefix
            backend:
              service:
                name: mmr
                port:
                  number: 8000

