apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmr
spec:
  template:
    spec:
      containers:
        - name: mmr
          volumeMounts:
            - name: mmr-local-storage
              mountPath: /data/media
      volumes:
        - name: mmr-local-storage
          persistentVolumeClaim:
            claimName: mmr-local-storage
